name: Workflow Scientifique - MAGNAKA DIBA MBOUDY

on:
  push:
    branches: [ "main" ]

jobs:
  validation-theoreme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Identification Scientifique
        run: |
          echo "Inventeur: MAGNAKA DIBA MBOUDY EULOGE HERVÃ‰ KASTOR"
          echo "Affiliation: INPTIC GABON | Prix CENAREST"
          echo "ORCID: 0009-0006-7558-9501"

      - name: Configuration Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Execution de l'IA de Simulation
        run: |
          pip install numpy
          python simulation_navier_stokes.py
